version: '3'
services: 
  opensearchrec_news_elasticsearch:
    image: elasticsearch:8.4.0
    environment:
      - network.host=0.0.0.0
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ELASTIC_USERNAME=$elasticsearch_username
      - ELASTIC_PASSWORD=$elasticsearch_password
      - xpack.security.enabled=true
      - cluster.routing.allocation.disk.watermark.low=2gb
      - cluster.routing.allocation.disk.watermark.high=1gb
      - cluster.routing.allocation.disk.watermark.flood_stage=512mb
    ports:
      - 9200:9200


